#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim options below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "jellybeans"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable Autocomplete Layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

# Enable Shell access directly from Vim 
[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 35

# Enable Colorcheme Layer
[[layers]]
    name = "colorscheme"

# Enable Javascript Language Layer
[[layers]]
    name = "lang#javascript"

# Enable Python Language Layer
[[layers]]
    name = "lang#python"

# Vim-Commentary: Comment selected text with 'gcc'
[[custom_plugins]]
    repo = "tpope/vim-commentary"
    merged = false

# Vim-Argwrap: Toggle whether args are wrapped with <leader><a>
[[custom_plugins]]
    repo = "FooSoft/vim-argwrap"
    merged = false

# Vim-GitGutter: Show changes on left margin from last commit
[[custom_plugins]]
    repo = "Fairblade/vim-gitgutter"
    merged = false

# Vim-Fugitive: Git versioning assist
[[custom_plugins]]
    repo = "tpope/vim-fugitive"
    merged = false

# Vim-Surround: Add surrounding symbols to selected text with <S><symbol> 
[[custom_plugins]]
    repo = "tpope/vim-surround"
    merged = false



